networks:
  app_network:
    name: ${APP_NAME}_network

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql8
    links:
      - "php:php_fpm"

  php:
    image: foxmark/php8.2.12-fpm:${PHP_IMAGE_VERSION}
    volumes:
      - ./app:/app
      - ./docker/php/config/99-php.ini:/usr/local/etc/php/conf.d/99-php.ini
      - ./docker/php/config/100-xdebug.ini:/usr/local/etc/php/conf.d/100-xdebug.ini
    user: "${UID}:${GID}"
    environment:
      - DATABASE_URL
    depends_on:
      - mysql8

  mysql8:
    image: mysql:${MYSQL_IMAGE_VERSION}
    container_name: mysql8
    user: "${UID}:${GID}"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
